### ISSUE TITLE
Include Vala syntax highlighting in vim

### ISSUE THREAD

**Issue by scythe** [elementary/os-patches#100]
I use vim. Just now I opened a `.vala` file in vim on Hera and noticed that it wasn't highlighted. I installed the Vala highlighting from here:

https://wiki.gnome.org/Projects/Vala/Tools/Vim

I think including this by default would make it easier for vim users to contribute to Elementary since Vala is the preferred development language and vim users are intransigent.

## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**
Vim syntax highlighting doesn't work on install for *most* elementary app source files (in Vala), because `vala.vim` and the corresponding lines in `filetype.vim` are not included on install for elementaryOS.

**Describe the solution you'd like**
Include existing Vala in vim syntax as above.

**Existing work**
Most operating systems try to support development in their preferred language using a variety of tools. Other OSs aren't based on Vala, of course.

**Describe alternatives you've considered**
There are no acceptable alternatives to vim, but vim users are stubborn enough to do the install manually, which is why it hasn't been fixed until now.

**Comment by tintou** [comment]
It would indeed be great but we don't maintain Vim ourselves, it would be better if someone contributed to vim directly and included the syntax highlighting file directly there as per the instructions in https://github.com/vim/vim/tree/master/runtime/syntax

**Comment by tintou** [comment]
I'm closing this since it is an issue with linked project
