### ISSUE TITLE
Ruby files always detected as Ruby on Rails

### ISSUE THREAD

**Issue by sixtyfive** [elementary/os-patches#114]
When opening a `.rb` file, Code selects "Ruby on Rails" as the programming language for syntax highlighting, but the file is not part of a Rails project. Not sure why Code isn't choosing "Ruby" (which is available as well) - tried with different files, they're always interpreted as "Ruby on Rails".

![image](https://user-images.githubusercontent.com/192860/47112010-64344380-d255-11e8-896d-13ca0d986d30.png)

**Comment by ryonakano** [comment]
Closing because we no longer patch gtksourceview since OS 7, and I confirmed Code detect .rb files as "Ruby" on OS 8 Early Access.
