### ISSUE TITLE
add-apt-repository fails on Error: could not find a distribution template for Elementary/next

### ISSUE THREAD

**Issue by AlexMikhalev** [elementary/os-patches#136]
```
  File "/usr/bin/add-apt-repository", line 108, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 118, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 613, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 91, in get_sources
    raise NoDistroTemplateException(
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Elementary/next
dpkg: error processing archive /var/cache/apt/archives/juno-drivers_0.3.12-3_amd64.deb (--unpack):

```
Every attempt to add repository (even via dpkg install dropbox or vscode) fails with error above as Elementary/Next isn't in distribution template. 
Changing /etc/lsb-release didn't help as lsb_release still returns Elementary/Next
```
$ sudo cat /etc/lsb-release 
DISTRIB_ID=ubuntu
DISTRIB_RELEASE=6.0
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="elementary OS 6.0 Next"
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Elementary
Description:	elementary OS 6.0 Next
Release:	6.0
Codename:	next
```
My understanding Elementary should present itself as ubuntu/focal to external repos, looking forward to set it up properly.

**Comment by AlexMikhalev** [comment]
Can't check it any more - moved to Pop OS.

**Comment by tintou** [comment]
Yes, this was previously handled by a patch. We can reapply the patch right before releasing elementary 6 if necessary.

**Comment by stsdc** [comment]
Still happens in recent builds:

```
Traceback (most recent call last):
  File "/usr/bin/apt-add-repository", line 108, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 118, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 613, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 91, in get_sources
    raise NoDistroTemplateException(
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Elementary/odin
```

It is troublesome, because I want to prepare my app for the Odin and need to install some software.

**Comment by pongloongyeat** [comment]
@cassidyjames you may want to add this to the Odin 6.0 project board so it doesn't get forgotten ;p before release

**Comment by maxie7** [comment]
I've got the same issue. After last updates (I use Elementary OS Odin) I have GNOME !!!!! no Pantheon DE, but I didn't change nothing!!! And in reconfigure of gdm3 or lightdm it doesn't appear either. I want my Pantheon DE back and have this:

```
sudo add-apt-repository ppa:elementary-os/daily                                                                                                                 ✔  22s   16:32:02   94%  
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 108, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 118, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 613, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 91, in get_sources
    raise NoDistroTemplateException(
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Elementary/odin
```

**Comment by AlexMikhalev** [comment]
@cassidyjames @pongloongyeat fellows it may seem like a minor thing to you, but this is a reason I completely switched to PopOS for my main laptop, despite being a backer (github sponsor) for elementary os.

**Comment by pongloongyeat** [comment]
@AlexMikhalev I've never used eOS 5 but from the comments above it seems that this was working on 5.0. Unfortunately, this is an issue on 6.0, which isn't a stable release as of yet.

<details><summary>Off-topic</summary>I wouldn't like to continue this discussion on why this is causing people to switch to other operating systems in this issue since it's unrelated but as an end user, I completely agree with you and understand what you mean. Unfortunately, I believe the eOS team is small and is working on tight finances so development will not be as fast as Pop!_OS. I'm sure the community would be happy to continue this off-topic discussion elsewhere like Reddit and I'd be more than happy to give more opinions of my own there as well! Cheers.</details>

**Comment by maxie7** [comment]
I've solved the problem (after some updates the pantheon entry had disappeared in display/login manager) by changing /usr/share/xsessions/pantheon.desktop file:
line >>> 'TryExec=io.elementary.wingpanel' with 'TryExec=/usr/bin/io.elementary.wingpanel

**Comment by danrabbit** [comment]
So, we are now patching python-apt in odin to use upstream LSB codename. I can confirm here that using `add-apt-repository` provides `focal` as the distro name.

If someone can still reproduce this issue, please provide the installation steps you are following to add an external repo. But for now, I believe this is fixed

**Comment by uwaiscode** [comment]
> **I've solved the problem in this way:**
> 
>     1. Type this command and press enter:
>        `sudo nano /etc/*-release`
>        (the instructions below are for nano text editor)
> 
>     2. Edit first file in this way:
> 
> 
> ```
> DISTRIB_ID=Ubuntu
> DISTRIB_RELEASE=20.04
> DISTRIB_CODENAME=focal
> DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
> ```
> 
> (you can copy the text I wrote you above)
> then save it with ctrl+O and close it with ctrl+X
> 3) After this you should see another text file opened in nano.
> This file you have to modify it as follows:
> 
> ```
> NAME="Ubuntu"
> VERSION="20.04.1 LTS (Focal Fossa)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 20.04.1 LTS"
> VERSION_ID="20.04"
> HOME_URL="https://www.ubuntu.com/"
> SUPPORT_URL="https://help.ubuntu.com/"
> BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
> PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
> VERSION_CODENAME=focal
> UBUNTU_CODENAME=focal
> ```
> 
> (as before you can copy the text I wrote above)
> then save it and close it as usually with ctrl+O and ctrl+X
> 4) Type 'reboot' to rebooting system and applying the modifies.
> 5) Repeat commands you were trying to execute and check if they works this time.
> 
> **I hope I was helpful!**

Thank you its work to me in elementary os 6 stable

**Comment by Alecaddd** [comment]
This issues is back on elementary OS 7, with the same error when trying to add this PPA:
`sudo add-apt-repository ppa:ubuntu-mozilla-daily/ppa`

Error output:
```
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 363, in <module>
    addaptrepo = AddAptRepository()
  File "/usr/bin/add-apt-repository", line 41, in __init__
    self.distro.get_sources(self.sourceslist)
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 91, in get_sources
    raise NoDistroTemplateException(
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Elementary/next
```

Should this issue be reopened or a dedicated one for OS 7 be created?

**Comment by danrabbit** [comment]
I'm tracking patches for jammy here: https://github.com/elementary/os-patches/issues/240

Looks like we haven't done the patch for python apt yet that would re-fix this
