### ISSUE TITLE
Touchégg causes session startup delay

### ISSUE THREAD

**Issue by davidmhewitt** [elementary/os-patches#140]
Touchégg uses GNOME session management keys in its desktop file:
https://github.com/elementary/os-patches/blob/042b7fd25921afd190fed2225650f08d8f94e6ac/installation/touchegg.desktop#L10-L12

But doesn't appear to actually register with the session manager.

This causes a 90 second delay in the desktop initialization phase. On an already setup system, this isn't very noticeable. The only effect is that the session isn't in the running state, meaning you can't log out/shutdown for those 90 seconds.

On a fresh install, this causes a 90 second delay before onboarding application launches, which is a bigger issue.

This should probably be reported upstream, but I'm opening this issue here so we can track it on the 6.0 release board.

**Comment by meisenzahl** [comment]
Can confirm

**Comment by JoseExposito** [comment]
Ooops, that should not be there. Just fixed it upstream. Thanks for the bug report, this was a tricky one to find!! Feel free to mention me in the future so I get notified

**Comment by danrabbit** [comment]
Since it seems 2.0.3 is right around the corner, I'm just gonna keep this issue open here as a reminder to import the next release

**Comment by davidmhewitt** [comment]
This appears to be resolved now.

2.0.3 is available in the repos, and I can see the autostart file has been updated.
