### ISSUE TITLE
Provide libmalcontent

### ISSUE THREAD

**Issue by tintou** [elementary/os-patches#147]
It is available from https://gitlab.freedesktop.org/pwithnall/malcontent/
Using this would allow us to have deeper integration in the greeter and the session itself, it would also allow us to remove the need of the Parental Control system daemon

**Comment by davidmhewitt** [comment]
I've created `malcontent-focal` and `malcontent-focal-patched` branches and tested a local build.

@tintou or @danrabbit could you look at setting up a recipe in launchpad?

We'll need to add it to the list of backports so the script can check for new versions in groovy once it's built in launchpad.

**Comment by danrabbit** [comment]
Created a recipe here: https://code.launchpad.net/~elementary-os/+recipe/malcontent-focal
