### ISSUE TITLE
Rebuild flatpak with malcontent support

### ISSUE THREAD

**Issue by davidmhewitt** [elementary/os-patches#149]
Flatpak detects whether malcontent is installed at build time and builds in support for parental controls using it if so.

Since malcontent isn't available in the Ubuntu 20.04 repos, the Ubuntu version of the package won't have those features.

If we want those, we'd need to add flatpak to os-patches and build it with a build-dep on malcontent.

**Comment by tintou** [comment]
[Currently building flatpak 1.8.3](https://code.launchpad.net/~elementary-os/+recipe/flatpak-focal) with malcontent support in staging PPA

**Comment by tintou** [comment]
It's now available
