### ISSUE TITLE
Package libportal

### ISSUE THREAD

**Issue by cassidyjames** [elementary/os-patches#179]
Builds fine locally on focal; would be nice for local development. https://github.com/flatpak/libportal/tree/master/portal-test

**Comment by tintou** [comment]
libportal is only useful in a container, if you only want the test app, you can consider shipping it as a flatpak as there is already a flatpak manifest available https://github.com/flatpak/libportal/blob/master/portal-test/flatpak/org.gnome.PortalTest.json

**Comment by danrabbit** [comment]
I think the problem is that if you add libportal to your app, then you now must always build and test it as Flatpak. It would no longer be possible to build and run it with meson because of the missing dependency

**Comment by tintou** [comment]
Yes, then you need conditional compilation because some libportal features aren't available outside of a Flatpak, also GLib-based apps probably don't need libportal at all as the features are already abstracted there.

**Comment by danrabbit** [comment]
That's a good point. Gonna bump this from the 6 project board until we see some use cases

**Comment by Marukesu** [comment]
In code, we need the OpenURI portal for `open in external application` (`open_uri` method with the ask flag ) and for the `open in file manager` (`open_directory` method).

The OpenURI portal can be used in non-sandboxed apps, so we don't need to do a check in that case.
