### ISSUE TITLE
Considered backports for EDS

### ISSUE THREAD

**Issue by tintou** [elementary/os-patches#182]
We still have several components on the OS side that rely on EDS from Focal, while it is relatively recent, we might benefit from several backports (only bug fixes, no ABI breaks)

To investigate:
 * [ ] https://gitlab.gnome.org/GNOME/evolution-data-server/-/commit/1a37ef016eefc71e1094964cb90a5201b57f01b5
 * [ ] https://gitlab.gnome.org/GNOME/evolution-data-server/-/commit/8133087c2a7ca033b249698df060e25b52409ee1
 * [ ] https://gitlab.gnome.org/GNOME/evolution-data-server/-/commit/f1750d633a8dd204d407386ee10feb8efa2a82c9
 * [ ] https://gitlab.gnome.org/GNOME/evolution-data-server/-/commit/7ced4d67aec74a4b162697f8a087e43777861aed
 * [ ] https://gitlab.gnome.org/GNOME/evolution-data-server/-/commit/c3eb2c82bc5c1b9dca3458b85e8321503ae91284
 * [ ] https://gitlab.gnome.org/GNOME/evolution-data-server/-/commit/d63a1ce3921a6a6c573a6a70dbf2e152adf74c3f
 * [ ] https://gitlab.gnome.org/GNOME/evolution-data-server/-/commit/1fb55ccfbae2e421222a67ea6a0159ea6cd22de6
 * [ ] https://gitlab.gnome.org/GNOME/evolution-data-server/-/commit/388e7298c2de641f0336313c92bfab24215b4d59
 * [ ] https://gitlab.gnome.org/GNOME/evolution-data-server/-/commit/be544df86f6a44f681ff0b1764c3fa0027cf3f0a
 * [ ] https://gitlab.gnome.org/GNOME/evolution-data-server/-/commit/2ce5132bf2cfc469b79472640ba9bdfe455e8144
 * [ ] https://gitlab.gnome.org/GNOME/evolution-data-server/-/commit/1cab1fb3e3121194be957a314608257f7e5b2b31
 * [ ] https://gitlab.gnome.org/GNOME/evolution-data-server/-/commit/6d58ee3a774853c53ae35a8c5a96468445f8544e
 * [ ] https://gitlab.gnome.org/GNOME/evolution-data-server/-/commit/326a7f096e74c03c71a75aa81994736f0a81dd58
 * [ ] https://gitlab.gnome.org/GNOME/evolution-data-server/-/commit/95a516250405b4ba3ab209bb25618ac97c4456b7
 * [ ] https://gitlab.gnome.org/GNOME/evolution-data-server/-/commit/558c0531f7b2964cc61110b7bda2a3f0fb433837

And maybe more

**Comment by marbetschar** [comment]
The UTF-7 to UTF-8 Conversion fix would potentially solve https://github.com/elementary/mail/issues/565 - so that'll be a great addition: https://gitlab.gnome.org/GNOME/evolution-data-server/-/issues/300

**Comment by tintou** [comment]
Let's close this
