### ISSUE TITLE
update-grub doesn't update anything

### ISSUE THREAD

**Issue by delight-aug** [elementary/os-patches#192]
## What Happened

I wanted to have kernel parameters, needed for my laptop to work correctly, used automatically. So, I added them to `GRUB_CMDLINE_LINUX_DEFAULT` property in `/etc/default/grub` and ran `update-grub` afterwards. However, when booting up, those parameters weren't applied — the boot menu entry had only `quiet splash $smth`.

## Expected Behavior

Kernel parameters I defined in `/etc/default/grub` had to be applied to the boot entry.

## Steps to Reproduce

1. Add or remove kernel parameters in the `GRUB_CMDLINE_LINUX_DEFAULT` property in `/etc/default/grub` configuration file
2. Run `update-grub` command with 'sudo'
3. Reboot to GRUB
4. Press `e` on any entry point
5. Verify there are no parameters at the end of `linux` line

### Logs

`sudo update-grub` output:
```
[sudo] password for maksym:         
Sourcing file `/etc/default/grub'
Sourcing file `/etc/default/grub.d/init-select.cfg'
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-5.11.0-25-generic
Found initrd image: /boot/initrd.img-5.11.0-25-generic
Adding boot menu entry for UEFI Firmware Settings
done
```

## Platform Information

![Screenshot from 2021-08-11 08 47 41](https://user-images.githubusercontent.com/51861383/129011899-08cf3766-8c12-44ce-8c10-d96914a4d613.png)

**Comment by tomaswarynyca** [comment]
Use `sudo grub-mkconfig -o /boot/efi/EFI/ubuntu/grub/grub.cfg`

**Comment by davidmhewitt** [comment]
This should now be resolved after a round of system updates and another `update-grub`. Please comment if not.
