### ISSUE TITLE
Backport Flatpak 1.12

### ISSUE THREAD

**Issue by Newbytee** [elementary/os-patches#214]
### Problem

Proton doesn't work with Steam via Flatpak.

### Proposal

Backport Flatpak 1.12! This request was suggested by an elementary OS developer on Reddit when I mentioned this in a thread: https://old.reddit.com/r/elementaryos/comments/phowfx/is_the_flatpak_version_of_steam_as_good_what/hbqq5f4/

See https://github.com/flatpak/flatpak/releases/tag/1.12.0

**Comment by tintou** [comment]
It should now be available in elementary OS 6
