### ISSUE TITLE
[Horus RC] Unpatched plank shipped

### ISSUE THREAD

**Issue by ryonakano** [elementary/os-patches#260]
### What Happened?

Horus RC comes with unpatched version (derived from the Ubuntu PPA) of plank, not our patched version.

This is because we don't have a designated recipe for jammy; `dock-juno`, `dock-focal`, and `dock-daily` exists but `dock-jammy` not: https://code.launchpad.net/~elementary-os/+recipes

### Steps to Reproduce

**Note that this issue refers the next "stable" branch of elementary OS, not the daily (early access) version***

1. Build the Horus RC using [our script](https://github.com/elementary/os)
2. Boot from the generated iso file
3. Run `LANG=C apt-cache policy plank`. You can see our PPA not listed there:

```
$ LANG=C apt-cache policy plank
plank:
  Installed: 0.11.89-4
  Candidate: 0.11.89-4
  Version table:
 *** 0.11.89-4 500
        500 mirror://mirrors.ubuntu.com/mirrors.txt jammy/universe amd64 Packages
        100 /var/lib/dpkg/status
```

![1](https://user-images.githubusercontent.com/26003928/202859311-aeb67061-375a-44aa-8fe1-d22540e0090f.png)

Also, you can see the launcher of plank in Applications menu since this is not the patched version:

![2](https://user-images.githubusercontent.com/26003928/202859285-369b92c3-24cf-4d1c-8217-c8c26de15404.png)

### Expected Behavior

Horus RC should come with the patched version of plank, as per the current daily version:

![スクリーンショット 2022-11-20 00 41 17](https://user-images.githubusercontent.com/26003928/202859583-ae961ff7-55a7-4cc7-bbfa-053264eb7011.png)

### OS Version

7.x (Next Stable)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
N/A
```

### Hardware Info

- VirtualBox 7.0.4 r154605

**Comment by danirabbit** [comment]
Should be built into the repo now! https://code.launchpad.net/~elementary-os/+recipe/dock-jammy

**Comment by ryonakano** [comment]
Today I built the stable iso again and confirmed it's now shipped with the patched version, thank you @danirabbit!

```bash
user@VirtualBox-6e7dc0c5:~$ LANG=C apt-cache policy plank
plank:
  Installed: 0.11.89+r1921+pkg7~ubuntu7.1
  Candidate: 0.11.89+r1921+pkg7~ubuntu7.1
  Version table:
 *** 0.11.89+r1921+pkg7~ubuntu7.1 500
        500 https://ppa.launchpadcontent.net/elementary-os/stable/ubuntu jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     0.11.89-4 500
        500 mirror://mirrors.ubuntu.com/mirrors.txt jammy/universe amd64 Packages
```

![スクリーンショット 2022-12-17 10 20 07](https://user-images.githubusercontent.com/26003928/208216244-beeea1f0-5796-4e55-9bad-30fefe089457.png)
