### ISSUE TITLE
`/etc/upstream-release/lsb-release` uses os-release format instead of lsb-release format

### ISSUE THREAD

**Issue by hasezoey** [elementary/os-patches#267]
Note: i am not sure where else to report this problem aside from here

---

I have noticed that elementaryOS (6.1) ships a `/etc/upstream-release/lsb-release` file, but that file is in os-release format instead of lsb-release format.

for example, the lsb-release format is used for `/etc/lsb-release`:

```txt
DISTRIB_ID=elementary
DISTRIB_RELEASE=6.1
DISTRIB_CODENAME=jolnir
DISTRIB_DESCRIPTION="elementary OS 6 Jólnir"
```

and the os-release format is used for `/etc/os-release`:

```txt
NAME="elementary OS"
VERSION="6.1 Jólnir"
ID=elementary
ID_LIKE=ubuntu
PRETTY_NAME="elementary OS 6.1 Jólnir"
LOGO=distributor-logo
VERSION_ID="6.1"
HOME_URL="https://elementary.io/"
DOCUMENTATION_URL="https://elementary.io/docs/learning-the-basics"
SUPPORT_URL="https://elementary.io/support"
BUG_REPORT_URL="https://github.com/elementary/triage/issues/new"
PRIVACY_POLICY_URL="https://elementary.io/privacy-policy"
VERSION_CODENAME=jolnir
UBUNTU_CODENAME=focal
```

and the current `/etc/upstream-release/lsb-release` file is:

```txt
ID=Ubuntu
VERSION_ID=20.04
VERSION_CODENAME=focal
PRETTY_NAME="Ubuntu 20.04.5 LTS"
```

originally noticed in https://github.com/nodkz/mongodb-memory-server/issues/735, where a user (probably running elementaryOS as host) has reported this, and i reproduced it in `elementary/docker:fe08f970723a` (docker image)

**Comment by tintou** [comment]
Thanks for noticing it, it is fixed for Jammy in https://github.com/elementary/os-patches/commit/a2592591200ae1fc333bb6b744787b76d7432987 and Focal in https://github.com/elementary/os-patches/commit/8d9a1b125bfd8bed296c15d2c4f55ac5339c1b70
