### ISSUE TITLE
Vue.js language spec

### ISSUE THREAD

**Issue by cassidyjames** [elementary/os-patches#28]
@btkostner wants this.

**Comment by Djaler** [comment]
What does this mean?

**Comment by codygarver** [comment]
I think he means someone else is going to add vue.js support to gtksourceview3-bionic-patched branch soon.

**Comment by stsdc** [comment]
Closing this since there is no patch anymore for gtksourceview for newer versions of elementary.
The language spec may be proposed in upstream project: https://gitlab.gnome.org/GNOME/gtksourceview
