### ISSUE TITLE
GSD power manager: Implement XcB randr API to control dislay backlight

### ISSUE THREAD

**Issue by yellowgh0st** [elementary/os-patches#31]
Can we provide more interfaces to control display brightness?

I have noticed that KDE Plasma desktop  can handle display brightness even when /sys/class/backlight interface isn't provided by GPU chipset driver.

See
https://github.com/KDE/powerdevil/tree/master/daemon/backends/upower

XCB RandR API
https://xcb.freedesktop.org/manual/group__XCB__RandR__API.html#details

**Comment by davidmhewitt** [comment]
Closing this issue as I don't think we have any intention to maintain patches to g-s-d that implement XRandR support.

It's not supported on many drivers these days and it won't work on Wayland.

It looks like KDE have dropped support for this too.
