### ISSUE TITLE
Upstream geoclue2 patch

### ISSUE THREAD

**Issue by worldofpeace** [elementary/os-patches#39]
I understand this was needed because of this issue https://github.com/elementary/default-settings/issues/17.

Until there is the ability to have a drop ins mechanism for additional config files like in https://gitlab.freedesktop.org/geoclue/geoclue/issues/74 it think it would be okay to upstream it (obviously without the deletions)

@davidmhewitt @codygarver

**Comment by worldofpeace** [comment]
This has been merged [here](https://gitlab.freedesktop.org/geoclue/geoclue/commit/2b0491e408be1ebcdbe8751bb2637c1acb78f71e).
It should be included in the next release whenever that is.

Also Zeeshan said:
>Btw vapi was included in the 2.4.11 release so you can ditch your own vapi file when you can depend on that version.
>

So [this](https://github.com/elementary/pantheon-agent-geoclue2/blob/master/vapi/libgeoclue-2.0.vapi) should be removed when you can.

**Comment by danrabbit** [comment]
Wow, thank you for submitting this patch upstream!

**Comment by worldofpeace** [comment]
No problem, all of it is an effort to get pantheon fully packaged in [NixOS](https://github.com/worldofpeace/nixpkgs/commits/elementary). Any changes that we can both benefit from will always be investigated.
