### ISSUE TITLE
Dual monitors HiDPI

### ISSUE THREAD

**Issue by jryden** [elementary/os-patches#42]
Not sure if this is a bug or a question... I have a Dell XPS 13 (3200x1800 resolution) and an external Dell monitor (1920x1200). HiDPI works great on the built-in Dell screen but makes everything on the external monitor colossal and basically unusable. Am I missing some way to not scale up everything on the external monitor? I'm running EOS 5.0 beta 2.

**Comment by jlnr** [comment]
There is no support for mixed DPI setups right now.

You could try `xrandr` as a workaround. In a terminal, first run `xrandr` without parameters to see what the name of the Dell monitor is (e.g. "HDMI-1"), and then run `xrandr --output HDMI-1 --scale 2x2` to scale everything down on that particular screen. (This assumes you are running in HiDPI mode.)

If that works reasonably well you could just add it as a startup application. In my experience, xrandr was a bit too glitchy with multiple screens attached.

**Comment by davidmhewitt** [comment]
There is nothing we can currently do about this in the `os-patches` repository, so I'm going to close this issue due to age.

There are various sources of information on this topic on the StackExchange site.
