### ISSUE TITLE
Contribute language-spect for Twig (PHP)

### ISSUE THREAD

**Issue by wout** [elementary/os-patches#43]
I prepared a Gtk language spec for [Twig](https://twig.symfony.com/). How can I submit this as a contribution?

**Comment by tintou** [comment]
This is the component we use for elementary Code
https://gitlab.gnome.org/GNOME/gtksourceview
Please submit it here

**Comment by wout** [comment]
Thanks, I'll commit it there!

**Comment by codygarver** [comment]
@wout when you get it into upstream master, open an issue here again and I will backport the fix so it's immediately available. Be sure to link the relevant upstream commit or merge proposal or bug.
