### ISSUE TITLE
Black/Non-responsive display after suspended while using HDMI

### ISSUE THREAD

**Issue by ghost** [elementary/os-patches#50]
When I'm connected to external monitor via HDMI, if the PC goes to sleep/suspend mode, upon returning to it, its unresponsive and I have to kill it using alt prt sc + R+E+I+S+U+B

**Comment by davidmhewitt** [comment]
Closing this issue as it's the wrong repo and this was more likely a problem with light-locker that we're not going to be shipping anymore.
