### ISSUE TITLE
Code App(Add): Missing Elixir syntax highlight. [GTKSourceView]

### ISSUE THREAD

**Issue by Marcos-Costa** [elementary/os-patches#52]
I've noticed that Code app is missing the syntax highlight for [Elixir](https://elixir-lang.org/). After browsing a little bit, I've found that [this issue](https://github.com/elementary/code/issues/539) was already open.
Since the [GTKViewSource](https://github.com/SteffenBauer/elixir-gtksourceview) was outdated, I've sent a [pull request](https://github.com/SteffenBauer/elixir-gtksourceview/pull/2) in order to update it to the current [Elixir Version - v 1.8](https://elixir-lang.org/blog/2019/01/14/elixir-v1-8-0-released/). 
The creator updated it and now, as mentioned by [David](https://github.com/elementary/code/issues/539#issuecomment-435018654), I would like to add this GTKViewSource file to elementary. 
What should I do?

**Comment by codygarver** [comment]
Here is our patched version of gtksourceview which includes backported language support like this, you should open a PR adding the relevant `.lang` file(s) in the dir ` data/language-specs/` and open a Pull Request against that branch and I will guide/help you with the rest.

https://github.com/elementary/os-patches/tree/gtksourceview3-bionic-patched

**Comment by Marcos-Costa** [comment]
[Done!](f314b54668d5bee972a7983e2c59cfc65ae15e37)

**Comment by codygarver** [comment]
I sent you a pull request for that branch, merge that and then open a pull request against https://github.com/elementary/os-patches, the `gtksourceview3-bionic-patched` branch

**Comment by Marcos-Costa** [comment]
[Done²](https://github.com/elementary/os-patches/pull/53)

**Comment by Marcos-Costa** [comment]
[Solved](https://github.com/elementary/os-patches/pull/53)
