### ISSUE TITLE
gxml-bionic recipe failed

### ISSUE THREAD

**Issue by BZHDeveloper** [elementary/os-patches#54]
This is due to invalid debian files. I've fixed this

see https://gitlab.gnome.org/BZHDeveloper/gxml/tree/debian-packaging or https://code.launchpad.net/~inizan-yannick/gxml/+git/gxml/+ref/debian-packaging

recipe with successful uploads https://code.launchpad.net/~inizan-yannick/+recipe/gxml-daily

**Comment by tintou** [comment]
We actually never shipped it, removed the branch as we moved to flatpak in focal
