### ISSUE TITLE
Patch mutter to fix graphical glitches in gala

### ISSUE THREAD

**Issue by worldofpeace** [elementary/os-patches#80]
## Describe the bug
See https://github.com/elementary/gala/issues/605#issuecomment-531613377.

We've used this patch in NixOS on mutter 3.28
* https://github.com/NixOS/nixpkgs/blob/139806d89d77a3c59785e4e59c00c7186e8e9ea6/pkgs/desktops/gnome-3/core/mutter/0001-Revert-ClutterActor-Preserve-valid-paint-volumes-til.patch

to workaround this issue. 

A fix in gala would be great, but I'm not sure if it's a problem in later version's of mutter.

**Comment by cassidyjames** [comment]
@tintou does this sound sane or do you know any more about it?

**Comment by worldofpeace** [comment]
You know, I've actually noticed this with mutter 3.34 as well.
I did mention budgie-desktop had the same issue and started doing
* https://github.com/solus-project/budgie-desktop/commit/65ea9b242e7721aee163662485c2f6ddc18c9fc5

**Comment by tintou** [comment]
@worldofpeace have you seen with upstream to include this in next releases?

**Comment by worldofpeace** [comment]
> @worldofpeace have you seen with upstream to include this in next releases?

Do you mean PR'ing this patch to mutter directly?
I haven't had any communication with upstream devs on this being an issue, see https://gitlab.gnome.org/GNOME/mutter/issues/536.

**Comment by worldofpeace** [comment]
I made some noise https://gitlab.gnome.org/GNOME/mutter/issues/536#note_724806

**Comment by hanaral** [comment]
It has been well over a year now and there hasn't been any movement on it. We can probably assume this won't be fixed in the next aeon or so.

**Comment by cassidyjames** [comment]
@tintou we talked about including this patch in standup; is that something you'd be comfortable with us doing?

**Comment by hanaral** [comment]
I'd like to point out again that this shouldn't be in the public beta or at least put an epilepsy warning about the unpatched bug:

https://user-images.githubusercontent.com/58219504/118399489-4a4d7e00-b655-11eb-9784-ec410aea5f47.mp4

Skip to 0:35 to see the high frequency flickering you can quite easily get, which could be quite bad if someone has a higher sensitivity towards this kind of flickering - it's certainly bad enough with my ADD.

**Comment by danrabbit** [comment]
Imported this patch to https://github.com/elementary/os-patches/tree/mutter-focal-patched

Building into staging for testing: https://code.launchpad.net/~elementary-os/+recipe/mutter-focal

**Comment by danrabbit** [comment]
This doesn't appear to happen anymore with the version of mutter in OS 7, so I'm gonna drop it from the project board
