### ISSUE TITLE
Import elementary-os-overlay sources

### ISSUE THREAD

**Issue by tintou** [elementary/os-patches#81]
The sources of the `elementary-os-overlay` package seem to be here https://code.launchpad.net/~elementary-os/elementaryos/os-patches-overlay-enabler
It'd be better to have it here on GitHub with the rest of the repository and with the proper README.md

**Comment by davidmhewitt** [comment]
For reference, the overlay package isn't necessary for the iso as the config is included during the iso build and ends up in the resulting installed system:
https://github.com/elementary/os/blob/master/etc/config/archives/patches.pref

However, the overlay package is probably still useful for things like docker images.

**Comment by ryonakano** [comment]
Just imported: https://github.com/elementary/elementary-os-overlay
