### ISSUE TITLE
Patch required patched packages for focal

### ISSUE THREAD

**Issue by davidmhewitt** [elementary/os-patches#91]
## Packages that we think may need patching (excluding packages mentioned below):

**`base-files`**
- [x] https://github.com/elementary/os-patches/commits/base-files-focal-patched

**`bash`**
- [x] https://github.com/elementary/os-patches/commits/bash-bionic-patched

**`dkms`**
- [x] Needs a patch for LSB: https://github.com/elementary/os-patches/commit/d7aeee58f167eaf120922f9d8dc58855b913d9a5

**`evince`**
- [x] Adds files to the apparmor profile: https://github.com/elementary/os-patches/commit/c93863166df9928a0f586a1c53858f67c8da34c2

Upstream issue filed here: https://bugs.launchpad.net/ubuntu/+source/evince/+bug/1915315

**`geoclue-2.0`**
- [x] Add our very secret MLS key: `e8792627-1f81-470e-a407-baecad8c7a4b`
- [x] We used to need to patch in our agent, but this is now supported upstream

**`grub2`**
- [x] Mostly theming stuff: https://github.com/elementary/os-patches/commits/grub2-bionic-patched

**`grub2-signed`**
- [x] It's not clear that this is actually patched? https://github.com/elementary/os-patches/compare/grub2-signed-bionic...grub2-signed-bionic-patched

**`gtksourceview4`**
- [x] * Increased contrast of spaces in solarized: https://github.com/elementary/os-patches/commit/0022abe3b4034566853db7e83d962ed622184970

**`language-selector`**
- [x] https://github.com/elementary/os-patches/commits/language-selector-bionic-patched

**`lsb`**
- [x] https://github.com/elementary/os-patches/commits/lsb-focal-patched

**`python-apt`**
- [x] https://github.com/elementary/os-patches/commits/python-apt-bionic-patched

**`unattended-upgrades`**
- [x] Use lsb -u https://github.com/elementary/os-patches/commits/unattended-upgrades-bionic-patched

**`xdg-user-dirs`**
- [ ] Removes Desktop handling https://github.com/elementary/os-patches/commit/e3c2c7a68dac8f653e234623888309a49b478d09

**`xdg-user-dirs-gtk`**
- [ ] Removes Desktop handling https://github.com/elementary/os-patches/commit/92b9d757c2867f30e66e8b2ecb0cc9a2b917a540

## Packages that are backports:
```
appstream:focal
mutter
packagekit:disco
```

## We don't ship/need need the following anymore:
```
live-build
ubiquity
```
**`file-roller`**
* This is its own package now: https://github.com/elementary/file-roller-contract

**`gnome-bluetooth`**
* Same as above: https://github.com/elementary/gnome-bluetooth-contract

**`gtksourceview3`**
* Added lang spec files, but if we really want to do this we should ship them with Code instead of patching: https://github.com/elementary/code/issues/950

**`network-manager-applet`**
Hide the connection editor desktop, but this only shows up in search, so who cares

**`software-properties`**
Stop installing unattended upgrades via recommends, but we don't ship this package by default and the long shutdown issue this supposedly causes can't be reproduced

## Required patches are now upstream:
```
desktop-file-utils
epiphany-browser
```
**`ibus`**
https://bugs.launchpad.net/ubuntu/+source/ibus/+bug/1835541

**`system-config-printer`**
Hide the .desktop, but this doesn't appear to show anymore

**`gnome-settings-daemon`**
* We used to drop an Ubuntu patch that caused a segfault, but it's now gone upstream and the crash is no longer reproducible 
* DPMS stuff isn't needed anymore since we updated the power plug to handle this correctly

But we need to go through the rest of the list and see if the patches are still required or if we can just use the upstream version.

**Comment by tintou** [comment]
Most of them are backports which don't need to be built for focal. I'm editing the original issue to show it clearly

**Comment by danrabbit** [comment]
epiphany shouldn't need any patches anymore since they're carrying everything we need upstream these days

**Comment by danrabbit** [comment]
Updated this with a lot more info today. There’s a few more packages we don’t need to patch anymore.

I’m really not sure what the BASH patches are intended to do. Is that so we get command names in the tab while it’s running instead of directory names?

**Comment by davidmhewitt** [comment]
This patch for grub is actually super important: https://github.com/elementary/os-patches/commit/5e7f14b37a82db195cb0f0082b5dfb2e2c69b9e5

It ensures the grub config is correctly updated after kernel updates etc. The reason we need this is caused by the fact we patch base-files to get a different lsb_release. We still want to use Ubuntu's signed bootloader, so we need to map elementary back to Ubuntu.

This is why someone was posting on reddit today about being unable to update their kernel:
https://www.reddit.com/r/elementaryos/comments/lhibby/odin_60_preview_cant_update_kernel/

**Comment by hanaral** [comment]
Shouldn't the mutter drawing bug also be patched?
